In [13]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import scale
import numpy as np

In [3]:
 my_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -4.3]])

In [4]:
print(my_data)

[[ 3.  -1.5  3.  -6.4]
 [ 0.   3.  -1.3  4.1]
 [ 1.   2.3 -2.9 -4.3]]


# Mean Removal

In [56]:
data_standardized = preprocessing.scale(my_data)
print(data_standardized)
print(data_standardized.mean(axis=0))
print(data_standardized.std(axis=0))

[[ 1.33630621 -1.39936232  1.36473933 -0.9258201 ]
 [-1.06904497  0.87670892 -0.36125453  1.38873015]
 [-0.26726124  0.5226534  -1.0034848  -0.46291005]]
[ 5.55111512e-17 -3.70074342e-17  0.00000000e+00 -1.85037171e-17]
[1. 1. 1. 1.]


# Scale the Data

In [69]:
scaler = MinMaxScaler()
print(scaler.fit(my_data))
print(scaler.transform(my_data))

MinMaxScaler(copy=True, feature_range=(0, 1))
[[1.         0.         1.         0.        ]
 [0.         1.         0.27118644 1.        ]
 [0.33333333 0.84444444 0.         0.2       ]]


# Normalize the data

In [73]:
preprocessing.normalize(my_data,'l2',0)

array([[ 0.9486833 , -0.36882768,  0.68644314, -0.73287781],
       [ 0.        ,  0.73765536, -0.2974587 ,  0.46949985],
       [ 0.31622777,  0.56553578, -0.6635617 , -0.49240228]])

# Binarize the data

In [74]:
preprocessing.binarize(my_data)

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 1., 0., 0.]])