# Numpy basics 

### 1)  Array creation

In [1]:
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)


[1. 2. 3.]
(3,)
float64


In [6]:
# create empty array
from numpy import empty
b = empty([3,3])
print("Print Empty Array ")
print(b)


Print Empty Array 
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.86160596e-321]
 [8.90060779e-307 9.05567908e-072 0.00000000e+000]]


### Why is this array not empty? 

In [9]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print("Create Array of Zeros")
print(a)

Create Array of Zeros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# create  array  of ones 

from numpy import ones
c= ones([5])
print(c)
print(c.dtype)

[1. 1. 1. 1. 1.]
float64


### 2)   Combining arrays 



In [13]:
#  Vertical stacking 
#-------------------------------

from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
#--
print(" vertically stacking arrays ")
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
 vertically stacking arrays 
[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
# Horizontal stacking 

from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


### 3) List to Arrays 



In [15]:
# 1D list to array 

from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [17]:
# lists of lists to 2D array 
# # create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))
print(data.shape)

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>
(3, 2)


### 4) Array Indexing 

In [18]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])


11
55


In [19]:
# two dimensional indexing 
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])


11


### 5) Array slicing 


In [20]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [21]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


In [22]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


### 6) Array reshaping 

In [24]:
# shape of 1D array 
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [26]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [27]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [28]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


In [29]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)


(3, 2)
(3, 2, 1)


#  Array Broadcasting

## Broadcasting : What is it? 

### Broadcasting is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size.
### Although the technique was developed for NumPy, it has also been adopted more broadly in other numerical computational libraries, such as Theano, TensorFlow, and Octave.

In [32]:
# broadcast  (add) a  scalar to one-dimensional array


from numpy import array
# define array
a = array([1, 2, 3])
print("1D array is : ", a)
# define scalar
b = 2
print("scalar is : ", b)
# broadcast
c = a + b
print(" c = a+b is : ",c)

1D array is :  [1 2 3]
scalar is :  2
 c = a+b is :  [3 4 5]


In [36]:
# broadcast scalar to two-dimensional array

from numpy import array
# define array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(" 2D Array is : ",A)
# define scalar
b = 2
print("Scalar is : ",b)
# broadcast
C = A + b
print("C = A + b is : ",C)

 2D Array is :  [[1 2 3]
 [1 2 3]]
Scalar is :  2
C = A + b is :  [[3 4 5]
 [3 4 5]]


In [ ]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define one-dimensional array
b = array([1, 2, 3])
print(b)
# broadcast
C = A + b
print(C)